linters:
  enable:
    - gosec
    - godot
    - misspell
    - staticcheck

run:
  go: '1.22'

issues:
  exclude-use-default: false

output:
  formats: colored-line-number

  # print lines of code with issue, default is true
  print-issue-lines: false

  # print linter name in the end of issue text, default is true
  print-linter-name: true