runtime: go121
main: ./cmd
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_thresold: 2
  success_thresold: 2
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_thresold: 2
  success_thresold: 2
  app_start_timeout_sec: 300