runtime: go121
main: ./cmd
automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.6
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300