version: "3.8"
services:
  api-min:
    profiles: ['prod']
    image: ghcr.io/blacknaml/hello-api:min
    port: 8080:8080
    build: .
  api-dev:
    profiles: ['dev']
    image: ghcr.io/blacknaml/hello-api:dev
    port: 8080:8080
    build:
      context: .
      target: dev          