version: "3.8"
services:
  database:
    image: redis:latest
    ports: 
      - 6379:6379
    volumes:
      - "./data/:/data/"
  api-min:
    profiles: ['prod']
    image: ghcr.io/blacknaml/hello-api:min
    ports: 
      - 8080:8080
    build: .
  api-dev:
    profiles: ['dev']
    image: ghcr.io/blacknaml/hello-api:dev
    ports: 
      - 8080:8080
    build:
      context: .
      target: dev  